CUSTOM_NAME=${CUSTOM_NAME:-tari-miner-hiveos}
CUSTOM_VERSION=1.1.7
CUSTOM_ALGO=cuckaroo29
CUSTOM_MINERBIN=start-c29.sh
CUSTOM_CONFIG_FILENAME=${CUSTOM_CONFIG_FILENAME:-/hive/miners/custom/$CUSTOM_NAME/miner.env}
CUSTOM_LOG_BASENAME=${CUSTOM_LOG_BASENAME:-/var/log/miner/$CUSTOM_NAME/tari-miner}
WEB_PORT=0
